from Generator import Factory


class ZHNameFactory(Factory):
    def __init__(self):
        pass

    def get(self):
        first = [
            '王', '李', '张', '刘', '陈', '杨', '黄', '吴', '赵', '周',
            '徐', '孙', '马', '朱', '胡', '林', '郭', '何', '高', '罗',
            '郑', '梁', '谢', '宋', '唐', '许', '邓', '冯', '韩', '曹',
            '曾', '彭', '萧', '蔡', '潘', '田', '董', '袁', '于', '余',
            '叶', '蒋', '杜', '苏', '魏', '程', '吕', '丁', '沈', '任',
            '姚', '卢', '傅', '钟', '姜', '崔', '谭', '廖', '范', '汪',
            '陆', '金', '石', '戴', '贾', '韦', '夏', '邱', '方', '侯',
            '邹', '熊', '孟', '秦', '白', '江', '阎', '薛', '尹', '段',
            '雷', '黎', '史', '龙', '陶', '贺', '顾', '毛', '郝', '龚',
            '邵', '万', '钱', '严', '赖', '覃', '洪', '武', '莫', '孔',
            '汤', '向', '常', '温', '康', '施', '文', '牛', '樊', '葛',
            '邢', '安', '齐', '易', '乔', '伍', '庞', '颜', '倪', '庄',
            '聂', '章', '鲁', '岳', '翟', '殷', '詹', '申', '欧', '耿',
            '关', '兰', '焦', '俞', '左', '柳', '甘', '祝', '包', '宁',
            '尚', '符', '舒', '阮', '柯', '纪', '梅', '童', '凌', '毕',
            '单', '季', '裴', '霍', '涂', '成', '苗', '谷', '盛', '曲',
            '翁', '冉', '骆', '蓝', '路', '游', '辛', '靳', '欧阳', '管',
            '柴', '蒙', '鲍', '华', '喻', '祁', '蒲', '房', '滕', '屈',
            '饶', '解', '牟', '艾', '尤', '阳', '时', '穆', '农', '司',
            '卓', '古', '吉', '缪', '简', '车', '项', '连', '芦', '麦',
            '褚', '娄', '窦', '戚', '岑', '景', '党', '宫', '费', '卜',
            '冷', '晏', '席', '卫', '米', '柏', '宗', '瞿', '桂', '全',
            '佟', '应', '臧', '闵', '苟', '邬', '边', '卞', '姬', '师',
            '和', '仇', '栾', '隋', '商', '刁', '沙', '荣', '巫', '寇',
            '桑', '郎', '甄', '丛', '仲', '虞', '敖', '巩', '明', '佘',
            '池', '查', '麻', '苑', '迟', '邝', '官', '封', '谈', '匡',
            '鞠', '惠', '荆', '乐', '冀', '郁', '胥', '南', '班', '储',
            '原', '栗', '燕', '楚', '鄢', '劳', '谌', '奚', '皮', '粟',
            '冼', '蔺', '楼', '盘', '满', '闻', '位', '厉', '伊', '仝',
            '区', '郜', '海', '阚', '花', '权', '强', '帅', '屠', '豆',
            '朴', '盖', '练', '廉', '禹', '井', '祖', '漆', '巴', '丰',
            '支', '卿', '国', '狄', '平', '计', '索', '宣', '晋', '相',
            '初', '门', '雲', '容', '敬', '来', '扈', '晁', '芮', '都',
            '普', '阙', '浦', '戈', '伏', '鹿', '薄', '邸', '雍', '辜',
            '羊', '阿', '乌', '母', '裘', '亓', '修', '邰', '赫', '杭',
            '况', '那', '宿', '鲜', '印', '逯', '隆', '茹', '诸', '战',
            '慕', '危', '玉', '银', '亢', '嵇', '公', '哈', '湛', '宾',
            '戎', '勾', '茅', '利', '於', '呼', '居', '揭', '干', '但',
            '尉', '冶', '斯', '元', '束', '檀', '衣', '信', '展', '阴',
            '昝', '智', '幸', '奉', '植', '衡', '富', '尧', '闭', '由'
        ]
        last = [
            '弈欣', '铭玟', '振洲', '玟铭', '金霞', '俞乐', '沛娴', '佳雪',
            '科峰', '先美', '曼菲', '亚飞', '修齐', '修宁', '修铭', '昱杉',
            '禧龙', '修宇', '镜豆', '嘉萱', '守钧', '二睿', '三睿', '灵睿',
            '邦理', '永琪', '仲虹', '仲红', '月文', '益铭', '屹铭', '小丹',
            '剑锋', '曼飞', '志虎', '家乐', '祖荣', '诗佳', '莫非', '伟奇',
            '志辉', '嘉韵', '乐斌', '雪佳', '德铭', '智虎', '治宽', '才先',
            '友聪', '少戈', '少彤', '少萱', '佳仪', '茜诺', '宇铭', '墨翰',
            '铭宇', '锦恺', '梓君', '元武', '生辉', '锦楷', '铭舜', '亿铭',
            '宇宣', '锦灿', '鱼童', '靖茹', '垚羽', '乐渔', '宇煊', '知渔',
            '志平', '知鱼', '晓英', '纪充', '一昌', '美思', '思希', '东周',
            '达道', '茜雯', '美麒', '悦婷', '妙绮', '剀漩', '嘉绮', '洪贞',
            '浏良', '文俊', '渔童', '桐汉', '旺祖', '玉琴', '军锋', '均严',
            '渔乐', '映霞', '裕洪', '材懿', '照东', '稼林', '润强', '会升',
            '宜驿', '谋发', '锦粲', '锦林', '敬旭', '酌琳', '婧怡', '波旭',
            '铭昊', '梓扬', '皓铭', '睿明', '国胜', '依欣', '晓愚', '乃明',
            '柔廷', '健雅', '梅欣', '小钢', '瑜怡', '秀华', '希茂', '迪明',
            '金美', '锦奕', '恩雅', '奕材', '悦佳', '创时', '宝熙', '勇昆',
            '垃圾', '星朋', '珺昱', '浚衍', '峻松', '俊衍', '浚焱', '亦铭',
            '钦渔', '楚娟', '眉嘉', '可儿', '丰珍', '俊俨', '汉熙', '维维',
            '好渔', '光吉', '新远', '瑛瑛', '志佳', '俊源', '义铭', '东航',
            '冰巧', '之槐', '香柳', '问春', '夏寒', '半香', '诗筠', '新梅', '白曼', '安波', '从阳', '含桃', '曼卉', '笑萍', '碧巧', '晓露', '寻菡', '沛白',
            '平灵', '水彤', '安彤', '涵易', '乐巧', '依风', '紫南', '亦丝', '易蓉', '紫萍', '惜萱', '诗蕾', '寻绿', '诗双', '寻云', '孤丹', '谷蓝', '惜香',
            '谷枫', '山灵', '幻丝', '友梅', '从云', '雁丝', '盼旋', '幼旋', '尔蓝', '沛山', '代丝', '痴梅', '觅松', '冰香', '依玉', '冰之', '妙梦', '以冬',
            '碧春', '曼青', '冷菱', '雪曼', '安白', '香桃', '安春', '千亦', '凌蝶', '又夏', '南烟。靖易', '沛凝', '翠梅', '书文', '雪卉', '乐儿', '傲丝',
            '安青',
            '初蝶', '寄灵', '惜寒', '雨竹', '冬莲', '绮南', '翠柏', '平凡', '亦玉', '孤兰', '秋珊', '新筠', '半芹', '夏瑶', '念文', '晓丝', '涵蕾', '雁凡',
            '谷兰', '灵凡', '凝云', '曼云', '丹彤', '南霜', '夜梦', '从筠', '雁芙', '语蝶', '依波', '晓旋', '念之', '盼芙', '曼安', '采珊', '盼夏', '初柳',
            '迎天', '曼安', '南珍', '妙芙', '语柳', '含莲', '晓筠', '夏山', '尔容', '采春', '念梦', '傲南', '问薇', '雨灵', '凝安', '冰海', '初珍', '宛菡',
            '冬卉', '盼晴', '冷荷', '寄翠', '幻梅', '如凡', '语梦', '易梦', '千柔', '向露', '梦玉', '傲霜', '依霜', '灵松', '诗桃', '书蝶', '恨真', '冰蝶',
            '山槐', '以晴', '友易', '梦桃', '香菱', '孤云', '水蓉', '雅容', '飞烟', '雁荷', '代芙', '醉易', '夏烟', '山梅', '若南', '恨桃', '依秋', '依波',
            '香巧', '紫萱', '涵易', '忆之', '幻巧', '水风', '安寒', '白亦', '惜玉', '碧春', '怜雪', '听南', '念蕾', '梦竹', '千凡', '寄琴', '采波', '元冬',
            '思菱', '平卉', '笑柳', '雪卉', '南蓉', '谷梦', '巧兰', '绿蝶', '飞荷', '平安', '孤晴', '芷荷', '曼冬', '寻巧', '寄波', '尔槐', '以旋', '绿蕊',
            '初夏', '依丝', '怜南', '千山', '雨安', '水风', '寄柔', '念巧', '幼枫', '凡桃', '新儿', '春翠', '夏波', '雨琴', '静槐', '元槐', '映阳', '飞薇',
            '小凝', '映寒', '傲菡', '谷蕊', '笑槐', '飞兰', '笑卉', '迎荷', '元冬', '书竹', '半烟', '绮波', '小之', '觅露', '夜雪', '春柔', '寒梦', '尔风',
            '白梅', '雨旋', '芷珊', '山彤', '尔柳', '沛柔', '灵萱', '沛凝', '白容', '乐蓉', '映安', '依云', '映冬', '凡雁', '梦秋', '醉柳', '梦凡', '秋巧',
            '若云', '元容', '怀蕾', '灵寒', '天薇', '白风', '访波', '亦凝', '易绿', '夜南', '曼凡', '亦巧', '青易', '冰真', '白萱', '友安', '诗翠', '雪珍',
            '海之',
            '小蕊', '又琴', '香彤', '语梦', '惜蕊', '迎彤', '沛白', '雁山', '易蓉', '雪晴', '诗珊', '春冬', '又绿', '冰绿', '半梅', '笑容', '沛凝', '念瑶',
            '天真', '含巧', '如冬', '向真', '从蓉', '春柔', '亦云', '向雁', '尔蝶', '冬易', '丹亦', '夏山', '醉香', '盼夏', '孤菱', '安莲', '问凝', '冬萱',
            '晓山', '雁蓉', '梦蕊', '山菡', '南莲', '飞双', '凝丝', '思萱', '怀梦', '雨梅', '冷霜', '向松', '迎丝', '迎梅', '听双', '山蝶', '夜梅', '醉冬',
            '巧云', '雨筠', '平文', '青文', '半蕾', '幼菱', '寻梅', '含之', '香之', '含蕊', '亦玉', '靖荷'
        ]
        return random.choice(first) + random.choice(last)


import random

from Generator import Factory


class ENNameFactory(Factory):
    __last_name_only = False

    def __init__(self, last_name_only = False):
        self.__last_name_only = last_name_only

    def get(self):
        first = [
            'Aaron', 'Abdul', 'Abe', 'Abel', 'Abraham', 'Abram', 'Adalberto', 'Adam', 'Adan', 'Adolfo', 'Adolph',
            'Adrian', 'Agustin', 'Ahmad', 'Ahmed', 'Al', 'Alan', 'Albert', 'Alberto', 'Alden', 'Aldo', 'Alec',
            'Alejandro', 'Alex', 'Alexander', 'Alexis', 'Alfonso', 'Alfonzo', 'Alfred', 'Alfredo', 'Ali', 'Allan',
            'Allen', 'Alonso', 'Alonzo', 'Alphonse', 'Alphonso', 'Alton', 'Alva', 'Alvaro', 'Alvin', 'Amado', 'Ambrose',
            'Amos', 'Anderson', 'Andre', 'Andrea', 'Andreas', 'Andres', 'Andrew', 'Andy', 'Angel', 'Angelo', 'Anibal',
            'Anthony', 'Antione', 'Antoine', 'Anton', 'Antone', 'Antonia', 'Antonio', 'Antony', 'Antwan', 'Archie',
            'Arden', 'Ariel', 'Arlen', 'Arlie', 'Armand', 'Armando', 'Arnold', 'Arnoldo', 'Arnulfo', 'Aron', 'Arron',
            'Art', 'Arthur', 'Arturo', 'Asa', 'Ashley', 'Aubrey', 'August', 'Augustine', 'Augustus', 'Aurelio',
            'Austin', 'Avery', 'Barney', 'Barrett', 'Barry', 'Bart', 'Barton', 'Basil', 'Beau', 'Ben', 'Benedict',
            'Benito', 'Benjamin', 'Bennett', 'Bennie', 'Benny', 'Benton', 'Bernard', 'Bernardo', 'Bernie', 'Berry',
            'Bert', 'Bertram', 'Bill', 'Billie', 'Billy', 'Blaine', 'Blair', 'Blake', 'Bo', 'Bob', 'Bobbie', 'Bobby',
            'Booker', 'Boris', 'Boyce', 'Boyd', 'Brad', 'Bradford', 'Bradley', 'Bradly', 'Brady', 'Brain', 'Branden',
            'Brandon', 'Brant', 'Brendan', 'Brendon', 'Brent', 'Brenton', 'Bret', 'Brett', 'Brian', 'Brice', 'Britt',
            'Brock', 'Broderick', 'Brooks', 'Bruce', 'Bruno', 'Bryan', 'Bryant', 'Bryce', 'Bryon', 'Buck', 'Bud',
            'Buddy', 'Buford', 'Burl', 'Burt', 'Burton', 'Buster', 'Byron', 'Caleb', 'Calvin', 'Cameron', 'Carey',
            'Carl', 'Carlo', 'Carlos', 'Carlton', 'Carmelo', 'Carmen', 'Carmine', 'Carol', 'Carrol', 'Carroll',
            'Carson', 'Carter', 'Cary', 'Casey', 'Cecil', 'Cedric', 'Cedrick', 'Cesar', 'Chad', 'Chadwick', 'Chance',
            'Chang', 'Charles', 'Charley', 'Charlie', 'Chas', 'Chase', 'Chauncey', 'Chester', 'Chet', 'Chi', 'Chong',
            'Chris', 'Christian', 'Christoper', 'Christopher', 'Chuck', 'Chung', 'Clair', 'Clarence', 'Clark', 'Claud',
            'Claude', 'Claudio', 'Clay', 'Clayton', 'Clement', 'Clemente', 'Cleo', 'Cletus', 'Cleveland', 'Cliff',
            'Clifford', 'Clifton', 'Clint', 'Clinton', 'Clyde', 'Cody', 'Colby', 'Cole', 'Coleman', 'Colin', 'Collin',
            'Colton', 'Columbus', 'Connie', 'Conrad', 'Cordell', 'Corey', 'Cornelius', 'Cornell', 'Cortez', 'Cory',
            'Courtney', 'Coy', 'Craig', 'Cristobal', 'Cristopher', 'Cruz', 'Curt', 'Curtis', 'Cyril', 'Cyrus', 'Dale',
            'Dallas', 'Dalton', 'Damian', 'Damien', 'Damion', 'Damon', 'Dan', 'Dana', 'Dane', 'Danial', 'Daniel',
            'Danilo', 'Dannie', 'Danny', 'Dante', 'Darell', 'Daren', 'Darin', 'Dario', 'Darius', 'Darnell', 'Daron',
            'Darrel', 'Darrell', 'Darren', 'Darrick', 'Darrin', 'Darron', 'Darryl', 'Darwin', 'Daryl', 'Dave', 'David',
            'Davis', 'Dean', 'Deandre', 'Deangelo', 'Dee', 'Del', 'Delbert', 'Delmar', 'Delmer', 'Demarcus',
            'Demetrius', 'Denis', 'Dennis', 'Denny', 'Denver', 'Deon', 'Derek', 'Derick', 'Derrick', 'Deshawn',
            'Desmond', 'Devin', 'Devon', 'Dewayne', 'Dewey', 'Dewitt', 'Dexter', 'Dick', 'Diego', 'Dillon', 'Dino',
            'Dion', 'Dirk', 'Domenic', 'Domingo', 'Dominic', 'Dominick', 'Dominique', 'Don', 'Donald', 'Dong', 'Donn',
            'Donnell', 'Donnie', 'Donny', 'Donovan', 'Donte', 'Dorian', 'Dorsey', 'Doug', 'Douglas', 'Douglass',
            'Doyle', 'Drew', 'Duane', 'Dudley', 'Duncan', 'Dustin', 'Dusty', 'Dwain', 'Dwayne', 'Dwight', 'Dylan',
            'Earl', 'Earle', 'Earnest', 'Ed', 'Eddie', 'Eddy', 'Edgar', 'Edgardo', 'Edison', 'Edmond', 'Edmund',
            'Edmundo', 'Eduardo', 'Edward', 'Edwardo', 'Edwin', 'Efrain', 'Efren', 'Elbert', 'Elden', 'Eldon',
            'Eldridge', 'Eli', 'Elias', 'Elijah', 'Eliseo', 'Elisha', 'Elliot', 'Elliott', 'Ellis', 'Ellsworth',
            'Elmer', 'Elmo', 'Eloy', 'Elroy', 'Elton', 'Elvin', 'Elvis', 'Elwood', 'Emanuel', 'Emerson', 'Emery',
            'Emil', 'Emile', 'Emilio', 'Emmanuel', 'Emmett', 'Emmitt', 'Emory', 'Enoch', 'Enrique', 'Erasmo', 'Eric',
            'Erich', 'Erick', 'Erik', 'Erin', 'Ernest', 'Ernesto', 'Ernie', 'Errol', 'Ervin', 'Erwin', 'Esteban',
            'Ethan', 'Eugene', 'Eugenio', 'Eusebio', 'Evan', 'Everett', 'Everette', 'Ezekiel', 'Ezequiel', 'Ezra',
            'Fabian', 'Faustino', 'Fausto', 'Federico', 'Felipe', 'Felix', 'Felton', 'Ferdinand', 'Fermin', 'Fernando',
            'Fidel', 'Filiberto', 'Fletcher', 'Florencio', 'Florentino', 'Floyd', 'Forest', 'Forrest', 'Foster',
            'Frances', 'Francesco', 'Francis', 'Francisco', 'Frank', 'Frankie', 'Franklin', 'Franklyn', 'Fred',
            'Freddie', 'Freddy', 'Frederic', 'Frederick', 'Fredric', 'Fredrick', 'Freeman', 'Fritz', 'Gabriel', 'Gail',
            'Gale', 'Galen', 'Garfield', 'Garland', 'Garret', 'Garrett', 'Garry', 'Garth', 'Gary', 'Gaston', 'Gavin',
            'Gayle', 'Gaylord', 'Genaro', 'Gene', 'Geoffrey', 'George', 'Gerald', 'Geraldo', 'Gerard', 'Gerardo',
            'German', 'Gerry', 'Gil', 'Gilbert', 'Gilberto', 'Gino', 'Giovanni', 'Giuseppe', 'Glen', 'Glenn', 'Gonzalo',
            'Gordon', 'Grady', 'Graham', 'Graig', 'Grant', 'Granville', 'Greg', 'Gregg', 'Gregorio', 'Gregory',
            'Grover', 'Guadalupe', 'Guillermo', 'Gus', 'Gustavo', 'Guy', 'Hai', 'Hal', 'Hank', 'Hans', 'Harlan',
            'Harland', 'Harley', 'Harold', 'Harris', 'Harrison', 'Harry', 'Harvey', 'Hassan', 'Hayden', 'Haywood',
            'Heath', 'Hector', 'Henry', 'Herb', 'Herbert', 'Heriberto', 'Herman', 'Herschel', 'Hershel', 'Hilario',
            'Hilton', 'Hipolito', 'Hiram', 'Hobert', 'Hollis', 'Homer', 'Hong', 'Horace', 'Horacio', 'Hosea', 'Houston',
            'Howard', 'Hoyt', 'Hubert', 'Huey', 'Hugh', 'Hugo', 'Humberto', 'Hung', 'Hunter', 'Hyman', 'Ian', 'Ignacio',
            'Ike', 'Ira', 'Irvin', 'Irving', 'Irwin', 'Isaac', 'Isaiah', 'Isaias', 'Isiah', 'Isidro', 'Ismael',
            'Israel', 'Isreal', 'Issac', 'Ivan', 'Ivory', 'Jacinto', 'Jack', 'Jackie', 'Jackson', 'Jacob', 'Jacques',
            'Jae', 'Jaime', 'Jake', 'Jamaal', 'Jamal', 'Jamar', 'Jame', 'Jamel', 'James', 'Jamey', 'Jamie', 'Jamison',
            'Jan', 'Jared', 'Jarod', 'Jarred', 'Jarrett', 'Jarrod', 'Jarvis', 'Jason', 'Jasper', 'Javier', 'Jay',
            'Jayson', 'Jc', 'Jean', 'Jed', 'Jeff', 'Jefferey', 'Jefferson', 'Jeffery', 'Jeffrey', 'Jeffry', 'Jerald',
            'Jeramy', 'Jere', 'Jeremiah', 'Jeremy', 'Jermaine', 'Jerold', 'Jerome', 'Jeromy', 'Jerrell', 'Jerrod',
            'Jerrold', 'Jerry', 'Jess', 'Jesse', 'Jessie', 'Jesus', 'Jewel', 'Jewell', 'Jim', 'Jimmie', 'Jimmy', 'Joan',
            'Joaquin', 'Jody', 'Joe', 'Joel', 'Joesph', 'Joey', 'John', 'Johnathan', 'Johnathon', 'Johnie', 'Johnnie',
            'Johnny', 'Johnson', 'Jon', 'Jonah', 'Jonas', 'Jonathan', 'Jonathon', 'Jordan', 'Jordon', 'Jorge', 'Jose',
            'Josef', 'Joseph', 'Josh', 'Joshua', 'Josiah', 'Jospeh', 'Josue', 'Juan', 'Jude', 'Judson', 'Jules',
            'Julian', 'Julio', 'Julius', 'Junior', 'Justin', 'Kareem', 'Karl', 'Kasey', 'Keenan', 'Keith', 'Kelley',
            'Kelly', 'Kelvin', 'Ken', 'Kendall', 'Kendrick', 'Keneth', 'Kenneth', 'Kennith', 'Kenny', 'Kent', 'Kenton',
            'Kermit', 'Kerry', 'Keven', 'Kevin', 'Kieth', 'Kim', 'King', 'Kip', 'Kirby', 'Kirk', 'Korey', 'Kory',
            'Kraig', 'Kris', 'Kristofer', 'Kristopher', 'Kurt', 'Kurtis', 'Kyle', 'Lacy', 'Lamar', 'Lamont', 'Lance',
            'Landon', 'Lane', 'Lanny', 'Larry', 'Lauren', 'Laurence', 'Lavern', 'Laverne', 'Lawerence', 'Lawrence',
            'Lazaro', 'Leandro', 'Lee', 'Leif', 'Leigh', 'Leland', 'Lemuel', 'Len', 'Lenard', 'Lenny', 'Leo', 'Leon',
            'Leonard', 'Leonardo', 'Leonel', 'Leopoldo', 'Leroy', 'Les', 'Lesley', 'Leslie', 'Lester', 'Levi', 'Lewis',
            'Lincoln', 'Lindsay', 'Lindsey', 'Lino', 'Linwood', 'Lionel', 'Lloyd', 'Logan', 'Lon', 'Long', 'Lonnie',
            'Lonny', 'Loren', 'Lorenzo', 'Lou', 'Louie', 'Louis', 'Lowell', 'Loyd', 'Lucas', 'Luciano', 'Lucien',
            'Lucio', 'Lucius', 'Luigi', 'Luis', 'Luke', 'Lupe', 'Luther', 'Lyle', 'Lyman', 'Lyndon', 'Lynn', 'Lynwood',
            'Mac', 'Mack', 'Major', 'Malcolm', 'Malcom', 'Malik', 'Man', 'Manual', 'Manuel', 'Marc', 'Marcel',
            'Marcelino', 'Marcellus', 'Marcelo', 'Marco', 'Marcos', 'Marcus', 'Margarito', 'Maria', 'Mariano', 'Mario',
            'Marion', 'Mark', 'Markus', 'Marlin', 'Marlon', 'Marquis', 'Marshall', 'Martin', 'Marty', 'Marvin', 'Mary',
            'Mason', 'Mathew', 'Matt', 'Matthew', 'Maurice', 'Mauricio', 'Mauro', 'Max', 'Maximo', 'Maxwell', 'Maynard',
            'Mckinley', 'Mel', 'Melvin', 'Merle', 'Merlin', 'Merrill', 'Mervin', 'Micah', 'Michael', 'Michal',
            'Michale', 'Micheal', 'Michel', 'Mickey', 'Miguel', 'Mike', 'Mikel', 'Milan', 'Miles', 'Milford', 'Millard',
            'Milo', 'Milton', 'Minh', 'Miquel', 'Mitch', 'Mitchel', 'Mitchell', 'Modesto', 'Mohamed', 'Mohammad',
            'Mohammed', 'Moises', 'Monroe', 'Monte', 'Monty', 'Morgan', 'Morris', 'Morton', 'Mose', 'Moses', 'Moshe',
            'Murray', 'Myles', 'Myron', 'Napoleon', 'Nathan', 'Nathanael', 'Nathanial', 'Nathaniel', 'Neal', 'Ned',
            'Neil', 'Nelson', 'Nestor', 'Neville', 'Newton', 'Nicholas', 'Nick', 'Nickolas', 'Nicky', 'Nicolas',
            'Nigel', 'Noah', 'Noble', 'Noe', 'Noel', 'Nolan', 'Norbert', 'Norberto', 'Norman', 'Normand', 'Norris',
            'Numbers', 'Octavio', 'Odell', 'Odis', 'Olen', 'Olin', 'Oliver', 'Ollie', 'Omar', 'Omer', 'Oren', 'Orlando',
            'Orval', 'Orville', 'Oscar', 'Osvaldo', 'Oswaldo', 'Otha', 'Otis', 'Otto', 'Owen', 'Pablo', 'Palmer',
            'Paris', 'Parker', 'Pasquale', 'Pat', 'Patricia', 'Patrick', 'Paul', 'Pedro', 'Percy', 'Perry', 'Pete',
            'Peter', 'Phil', 'Philip', 'Phillip', 'Pierre', 'Porfirio', 'Porter', 'Preston', 'Prince', 'Quentin',
            'Quincy', 'Quinn', 'Quintin', 'Quinton', 'Rafael', 'Raleigh', 'Ralph', 'Ramiro', 'Ramon', 'Randal',
            'Randall', 'Randell', 'Randolph', 'Randy', 'Raphael', 'Rashad', 'Raul', 'Ray', 'Rayford', 'Raymon',
            'Raymond', 'Raymundo', 'Reed', 'Refugio', 'Reggie', 'Reginald', 'Reid', 'Reinaldo', 'Renaldo', 'Renato',
            'Rene', 'Reuben', 'Rex', 'Rey', 'Reyes', 'Reynaldo', 'Rhett', 'Ricardo', 'Rich', 'Richard', 'Richie',
            'Rick', 'Rickey', 'Rickie', 'Ricky', 'Rico', 'Rigoberto', 'Riley', 'Rob', 'Robbie', 'Robby', 'Robert',
            'Roberto', 'Robin', 'Robt', 'Rocco', 'Rocky', 'Rod', 'Roderick', 'Rodger', 'Rodney', 'Rodolfo', 'Rodrick',
            'Rodrigo', 'Rogelio', 'Roger', 'Roland', 'Rolando', 'Rolf', 'Rolland', 'Roman', 'Romeo', 'Ron', 'Ronald',
            'Ronnie', 'Ronny', 'Roosevelt', 'Rory', 'Rosario', 'Roscoe', 'Rosendo', 'Ross', 'Roy', 'Royal', 'Royce',
            'Ruben', 'Rubin', 'Rudolf', 'Rudolph', 'Rudy', 'Rueben', 'Rufus', 'Rupert', 'Russ', 'Russel', 'Russell',
            'Rusty', 'Ryan', 'Sal', 'Salvador', 'Salvatore', 'Sam', 'Sammie', 'Sammy', 'Samual', 'Samuel', 'Sandy',
            'Sanford', 'Sang', 'Santiago', 'Santo', 'Santos', 'Saul', 'Scot', 'Scott', 'Scottie', 'Scotty', 'Sean',
            'Sebastian', 'Sergio', 'Seth', 'Seymour', 'Shad', 'Shane', 'Shannon', 'Shaun', 'Shawn', 'Shayne', 'Shelby',
            'Sheldon', 'Shelton', 'Sherman', 'Sherwood', 'Shirley', 'Shon', 'Sid', 'Sidney', 'Silas', 'Simon', 'Sol',
            'Solomon', 'Son', 'Sonny', 'Spencer', 'Stacey', 'Stacy', 'Stan', 'Stanford', 'Stanley', 'Stanton', 'Stefan',
            'Stephan', 'Stephen', 'Sterling', 'Steve', 'Steven', 'Stevie', 'Stewart', 'Stuart', 'Sung', 'Sydney',
            'Sylvester', 'Tad', 'Tanner', 'Taylor', 'Ted', 'Teddy', 'Teodoro', 'Terence', 'Terrance', 'Terrell',
            'Terrence', 'Terry', 'Thad', 'Thaddeus', 'Thanh', 'Theo', 'Theodore', 'Theron', 'Thomas', 'Thurman', 'Tim',
            'Timmy', 'Timothy', 'Titus', 'Tobias', 'Toby', 'Tod', 'Todd', 'Tom', 'Tomas', 'Tommie', 'Tommy', 'Toney',
            'Tony', 'Tory', 'Tracey', 'Tracy', 'Travis', 'Trent', 'Trenton', 'Trevor', 'Trey', 'Trinidad', 'Tristan',
            'Troy', 'Truman', 'Tuan', 'Ty', 'Tyler', 'Tyree', 'Tyrell', 'Tyron', 'Tyrone', 'Tyson', 'Ulysses', 'Val',
            'Valentin', 'Valentine', 'Van', 'Vance', 'Vaughn', 'Vern', 'Vernon', 'Vicente', 'Victor', 'Vince',
            'Vincent', 'Vincenzo', 'Virgil', 'Virgilio', 'Vito', 'Von', 'Wade', 'Waldo', 'Walker', 'Wallace', 'Wally',
            'Walter', 'Walton', 'Ward', 'Warner', 'Warren', 'Waylon', 'Wayne', 'Weldon', 'Wendell', 'Werner', 'Wes',
            'Wesley', 'Weston', 'Whitney', 'Wilber', 'Wilbert', 'Wilbur', 'Wilburn', 'Wiley', 'Wilford', 'Wilfred',
            'Wilfredo', 'Will', 'Willard', 'William', 'Williams', 'Willian', 'Willie', 'Willis', 'Willy', 'Wilmer',
            'Wilson', 'Wilton', 'Winford', 'Winfred', 'Winston', 'Wm', 'Woodrow', 'Wyatt', 'Xavier', 'Yong', 'Young',
            'Zachariah', 'Zachary', 'Zachery', 'Zack', 'Zackary', 'Zane',
        ]
        last = [
            'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Garcia', 'Rodriguez', 'Wilson',
            'Martinez', 'Anderson', 'Taylor', 'Thomas', 'Hernandez', 'Moore', 'Martin', 'Jackson', 'Thompson', 'White',
            'Lopez', 'Lee', 'Gonzalez', 'Harris', 'Clark', 'Lewis', 'Robinson', 'Walker', 'Perez', 'Hall', 'Young',
            'Allen', 'Sanchez', 'Wright', 'King', 'Scott', 'Green', 'Baker', 'Adams', 'Nelson', 'Hill', 'Ramirez',
            'Campbell', 'Mitchell', 'Roberts', 'Carter', 'Phillips', 'Evans', 'Turner', 'Torres', 'Parker', 'Collins',
            'Edwards', 'Stewart', 'Flores', 'Morris', 'Nguyen', 'Murphy', 'Rivera', 'Cook', 'Rogers', 'Morgan',
            'Peterson', 'Cooper', 'Reed', 'Bailey', 'Bell', 'Gomez', 'Kelly', 'Howard', 'Ward', 'Cox', 'Diaz',
            'Richardson', 'Wood', 'Watson', 'Brooks', 'Bennett', 'Gray', 'James', 'Reyes', 'Cruz', 'Hughes', 'Price',
            'Myers', 'Long', 'Foster', 'Sanders', 'Ross', 'Morales', 'Powell', 'Sullivan', 'Russell', 'Ortiz',
            'Jenkins', 'Gutierrez', 'Perry', 'Butler', 'Barnes', 'Fisher', 'Henderson', 'Coleman', 'Simmons',
            'Patterson', 'Jordan', 'Reynolds', 'Hamilton', 'Graham', 'Kim', 'Gonzales', 'Alexander', 'Ramos', 'Wallace',
            'Griffin', 'West', 'Cole', 'Hayes', 'Chavez', 'Gibson', 'Bryant', 'Ellis', 'Stevens', 'Murray', 'Ford',
            'Marshall', 'Owens', 'Mcdonald', 'Harrison', 'Ruiz', 'Kennedy', 'Wells', 'Alvarez', 'Woods', 'Mendoza',
            'Castillo', 'Olson', 'Webb', 'Washington', 'Tucker', 'Freeman', 'Burns', 'Henry', 'Vasquez', 'Snyder',
            'Simpson', 'Crawford', 'Jimenez', 'Porter', 'Mason', 'Shaw', 'Gordon', 'Wagner', 'Hunter', 'Romero',
            'Hicks', 'Dixon', 'Hunt', 'Palmer', 'Robertson', 'Black', 'Holmes', 'Stone', 'Meyer', 'Boyd', 'Mills',
            'Warren', 'Fox', 'Rose', 'Rice', 'Moreno', 'Schmidt', 'Patel', 'Ferguson', 'Nichols', 'Herrera', 'Medina',
            'Ryan', 'Fernandez', 'Weaver', 'Daniels', 'Stephens', 'Gardner', 'Payne', 'Kelley', 'Dunn', 'Pierce',
            'Arnold', 'Tran', 'Spencer', 'Peters', 'Hawkins', 'Grant', 'Hansen', 'Castro', 'Hoffman', 'Hart', 'Elliott',
            'Cunningham', 'Knight', 'Bradley', 'Carroll', 'Hudson', 'Duncan', 'Armstrong', 'Berry', 'Andrews',
            'Johnston', 'Ray', 'Lane', 'Riley', 'Carpenter', 'Perkins', 'Aguilar', 'Silva', 'Richards', 'Willis',
            'Matthews', 'Chapman', 'Lawrence', 'Garza', 'Vargas', 'Watkins', 'Wheeler', 'Larson', 'Carlson', 'Harper',
            'George', 'Greene', 'Burke', 'Guzman', 'Morrison', 'Munoz', 'Jacobs', 'Obrien', 'Lawson', 'Franklin',
            'Lynch', 'Bishop', 'Carr', 'Salazar', 'Austin', 'Mendez', 'Gilbert', 'Jensen', 'Williamson', 'Montgomery',
            'Harvey', 'Oliver', 'Howell', 'Dean', 'Hanson', 'Weber', 'Garrett', 'Sims', 'Burton', 'Fuller', 'Soto',
            'Mccoy', 'Welch', 'Chen', 'Schultz', 'Walters', 'Reid', 'Fields', 'Walsh', 'Little', 'Fowler', 'Bowman',
            'Davidson', 'May', 'Day', 'Schneider', 'Newman', 'Brewer', 'Lucas', 'Holland', 'Wong', 'Banks', 'Santos',
            'Curtis', 'Pearson', 'Delgado', 'Valdez', 'Pena', 'Rios', 'Douglas', 'Sandoval', 'Barrett', 'Hopkins',
            'Keller', 'Guerrero', 'Stanley', 'Bates', 'Alvarado', 'Beck', 'Ortega', 'Wade', 'Estrada', 'Contreras',
            'Barnett', 'Caldwell', 'Santiago', 'Lambert', 'Powers', 'Chambers', 'Nunez', 'Craig', 'Leonard', 'Lowe',
            'Rhodes', 'Byrd', 'Gregory', 'Shelton', 'Frazier', 'Becker', 'Maldonado', 'Fleming', 'Vega', 'Sutton',
            'Cohen', 'Jennings', 'Parks', 'Mcdaniel', 'Watts', 'Barker', 'Norris', 'Vaughn', 'Vazquez', 'Holt',
            'Schwartz', 'Steele', 'Benson', 'Neal', 'Dominguez', 'Horton', 'Terry', 'Wolfe', 'Hale', 'Lyons', 'Graves',
            'Haynes', 'Miles', 'Park', 'Warner', 'Padilla', 'Bush', 'Thornton', 'Mccarthy', 'Mann', 'Zimmerman',
            'Erickson', 'Fletcher', 'Mckinney', 'Page', 'Dawson', 'Joseph', 'Marquez', 'Reeves', 'Klein', 'Espinoza',
            'Baldwin', 'Moran', 'Love', 'Robbins', 'Higgins', 'Ball', 'Cortez', 'Le', 'Griffith', 'Bowen', 'Sharp',
            'Cummings', 'Ramsey', 'Hardy', 'Swanson', 'Barber', 'Acosta', 'Luna', 'Chandler', 'Daniel', 'Blair',
            'Cross', 'Simon', 'Dennis', 'Oconnor', 'Quinn', 'Gross', 'Navarro', 'Moss', 'Fitzgerald', 'Doyle',
            'Mclaughlin', 'Rojas', 'Rodgers', 'Stevenson', 'Singh', 'Yang', 'Figueroa', 'Harmon', 'Newton', 'Paul',
            'Manning', 'Garner', 'Mcgee', 'Reese', 'Francis', 'Burgess', 'Adkins', 'Goodman', 'Curry', 'Brady',
            'Christensen', 'Potter', 'Walton', 'Goodwin', 'Mullins', 'Molina', 'Webster', 'Fischer', 'Campos', 'Avila',
            'Sherman', 'Todd', 'Chang', 'Blake', 'Malone', 'Wolf', 'Hodges', 'Juarez', 'Gill', 'Farmer', 'Hines',
            'Gallagher', 'Duran', 'Hubbard', 'Cannon', 'Miranda', 'Wang', 'Saunders', 'Tate', 'Mack', 'Hammond',
            'Carrillo', 'Townsend', 'Wise', 'Ingram', 'Barton', 'Mejia', 'Ayala', 'Schroeder', 'Hampton', 'Rowe',
            'Parsons', 'Frank', 'Waters', 'Strickland', 'Osborne', 'Maxwell', 'Chan', 'Deleon', 'Norman', 'Harrington',
            'Casey', 'Patton', 'Logan', 'Bowers', 'Mueller', 'Glover', 'Floyd', 'Hartman', 'Buchanan', 'Cobb', 'French',
            'Kramer', 'Mccormick', 'Clarke', 'Tyler', 'Gibbs', 'Moody', 'Conner', 'Sparks', 'Mcguire', 'Leon', 'Bauer',
            'Norton', 'Pope', 'Flynn', 'Hogan', 'Robles', 'Salinas', 'Yates', 'Lindsey', 'Lloyd', 'Marsh', 'Mcbride',
            'Owen', 'Solis', 'Pham', 'Lang', 'Pratt', 'Lara', 'Brock', 'Ballard', 'Trujillo', 'Shaffer', 'Drake',
            'Roman', 'Aguirre', 'Morton', 'Stokes', 'Lamb', 'Pacheco', 'Patrick', 'Cochran', 'Shepherd', 'Cain',
            'Burnett', 'Hess', 'Li', 'Cervantes', 'Olsen', 'Briggs', 'Ochoa', 'Cabrera', 'Velasquez', 'Montoya', 'Roth',
            'Meyers', 'Cardenas', 'Fuentes', 'Weiss', 'Wilkins', 'Hoover', 'Nicholson', 'Underwood', 'Short', 'Carson',
            'Morrow', 'Colon', 'Holloway', 'Summers', 'Bryan', 'Petersen', 'Mckenzie', 'Serrano', 'Wilcox', 'Carey',
            'Clayton', 'Poole', 'Calderon', 'Gallegos', 'Greer', 'Rivas', 'Guerra', 'Decker', 'Collier', 'Wall',
            'Whitaker', 'Bass', 'Flowers', 'Davenport', 'Conley', 'Houston', 'Huff', 'Copeland', 'Hood', 'Monroe',
            'Massey', 'Roberson', 'Combs', 'Franco', 'Larsen', 'Pittman', 'Randall', 'Skinner', 'Wilkinson', 'Kirby',
            'Cameron', 'Bridges', 'Anthony', 'Richard', 'Kirk', 'Bruce', 'Singleton', 'Mathis', 'Bradford', 'Boone',
            'Abbott', 'Charles', 'Allison', 'Sweeney', 'Atkinson', 'Horn', 'Jefferson', 'Rosales', 'York', 'Christian',
            'Phelps', 'Farrell', 'Castaneda', 'Nash', 'Dickerson', 'Bond', 'Wyatt', 'Foley', 'Chase', 'Gates',
            'Vincent', 'Mathews', 'Hodge', 'Garrison', 'Trevino', 'Villarreal', 'Heath', 'Dalton', 'Valencia',
            'Callahan', 'Hensley', 'Atkins', 'Huffman', 'Roy', 'Boyer', 'Shields', 'Lin', 'Hancock', 'Grimes', 'Glenn',
            'Cline', 'Delacruz', 'Camacho', 'Dillon', 'Parrish', 'Oneill', 'Melton', 'Booth', 'Kane', 'Berg', 'Harrell',
            'Pitts', 'Savage', 'Wiggins', 'Brennan', 'Salas', 'Marks', 'Russo', 'Sawyer', 'Baxter', 'Golden',
            'Hutchinson', 'Liu', 'Walter', 'Mcdowell', 'Wiley', 'Rich', 'Humphrey', 'Johns', 'Koch', 'Suarez', 'Hobbs',
            'Beard', 'Gilmore', 'Ibarra', 'Keith', 'Macias', 'Khan', 'Andrade', 'Ware', 'Stephenson', 'Henson',
            'Wilkerson', 'Dyer', 'Mcclure', 'Blackwell', 'Mercado', 'Tanner', 'Eaton', 'Clay', 'Barron', 'Beasley',
            'Oneal', 'Small', 'Preston', 'Wu', 'Zamora', 'Macdonald', 'Vance', 'Snow', 'Mcclain', 'Stafford', 'Orozco',
            'Barry', 'English', 'Shannon', 'Kline', 'Jacobson', 'Woodard', 'Huang', 'Kemp', 'Mosley', 'Prince',
            'Merritt', 'Hurst', 'Villanueva', 'Roach', 'Nolan', 'Lam', 'Yoder', 'Mccullough', 'Lester', 'Santana',
            'Valenzuela', 'Winters', 'Barrera', 'Orr', 'Leach', 'Berger', 'Mckee', 'Strong', 'Conway', 'Stein',
            'Whitehead', 'Bullock', 'Escobar', 'Knox', 'Meadows', 'Solomon', 'Velez', 'Odonnell', 'Kerr', 'Stout',
            'Blankenship', 'Browning', 'Kent', 'Lozano', 'Bartlett', 'Pruitt', 'Buck', 'Barr', 'Gaines', 'Durham',
            'Gentry', 'Mcintyre', 'Sloan', 'Rocha', 'Melendez', 'Herman', 'Sexton', 'Moon', 'Hendricks', 'Rangel',
            'Stark', 'Lowery', 'Hardin', 'Hull', 'Sellers', 'Ellison', 'Calhoun', 'Gillespie', 'Mora', 'Knapp',
            'Mccall', 'Morse', 'Dorsey', 'Weeks', 'Nielsen', 'Livingston', 'Leblanc', 'Mclean', 'Bradshaw', 'Glass',
            'Middleton', 'Buckley', 'Schaefer', 'Frost', 'Howe', 'House', 'Mcintosh', 'Ho', 'Pennington', 'Reilly',
            'Hebert', 'Mcfarland', 'Hickman', 'Noble', 'Spears', 'Conrad', 'Arias', 'Galvan', 'Velazquez', 'Huynh',
            'Frederick', 'Randolph', 'Cantu', 'Fitzpatrick', 'Mahoney', 'Peck', 'Villa', 'Michael', 'Donovan',
            'Mcconnell', 'Walls', 'Boyle', 'Mayer', 'Zuniga', 'Giles', 'Pineda', 'Pace', 'Hurley', 'Mays', 'Mcmillan',
            'Crosby', 'Ayers', 'Case', 'Bentley', 'Shepard', 'Everett', 'Pugh', 'David', 'Mcmahon', 'Dunlap', 'Bender',
            'Hahn', 'Harding', 'Acevedo', 'Raymond', 'Blackburn', 'Duffy', 'Landry', 'Dougherty', 'Bautista', 'Shah',
            'Potts', 'Arroyo', 'Valentine', 'Meza', 'Gould', 'Vaughan', 'Fry', 'Rush', 'Avery', 'Herring', 'Dodson',
            'Clements', 'Sampson', 'Tapia', 'Bean', 'Lynn', 'Crane', 'Farley', 'Cisneros', 'Benton', 'Ashley', 'Mckay',
            'Finley', 'Best', 'Blevins', 'Friedman', 'Moses', 'Sosa', 'Blanchard', 'Huber', 'Frye', 'Krueger',
            'Bernard', 'Rosario', 'Rubio', 'Mullen', 'Benjamin', 'Haley', 'Chung', 'Moyer', 'Choi', 'Horne', 'Yu',
            'Woodward', 'Ali', 'Nixon', 'Hayden', 'Rivers', 'Estes', 'Mccarty', 'Richmond', 'Stuart', 'Maynard',
            'Brandt', 'Oconnell', 'Hanna', 'Sanford', 'Sheppard', 'Church', 'Burch', 'Levy', 'Rasmussen', 'Coffey',
            'Ponce', 'Faulkner', 'Donaldson', 'Schmitt', 'Novak', 'Costa', 'Montes', 'Booker', 'Cordova', 'Waller',
            'Arellano', 'Maddox', 'Mata', 'Bonilla', 'Stanton', 'Compton', 'Kaufman', 'Dudley', 'Mcpherson', 'Beltran',
            'Dickson', 'Mccann', 'Villegas', 'Proctor', 'Hester', 'Cantrell', 'Daugherty', 'Cherry', 'Bray', 'Davila',
            'Rowland', 'Madden', 'Levine', 'Spence', 'Good', 'Irwin', 'Werner', 'Krause', 'Petty', 'Whitney', 'Baird',
            'Hooper', 'Pollard', 'Zavala', 'Jarvis', 'Holden', 'Hendrix', 'Haas', 'Mcgrath', 'Bird', 'Lucero',
            'Terrell', 'Riggs', 'Joyce', 'Rollins', 'Mercer', 'Galloway', 'Duke', 'Odom', 'Andersen', 'Downs',
            'Hatfield', 'Benitez', 'Archer', 'Huerta', 'Travis', 'Mcneil', 'Hinton', 'Zhang', 'Hays', 'Mayo', 'Fritz',
            'Branch', 'Mooney', 'Ewing', 'Ritter', 'Esparza', 'Frey', 'Braun', 'Gay', 'Riddle', 'Haney', 'Kaiser',
            'Holder', 'Chaney', 'Mcknight', 'Gamble', 'Vang', 'Cooley', 'Carney', 'Cowan', 'Forbes', 'Ferrell',
            'Davies', 'Barajas', 'Shea', 'Osborn', 'Bright', 'Cuevas', 'Bolton', 'Murillo', 'Lutz', 'Duarte', 'Kidd',
            'Key', 'Cook'
        ]
        if not self.__last_name_only:
            return random.choice(first) +' ' + random.choice(last)
        else:
            return random.choice(last)
